### ISSUE TITLE
Admin access to readthedocs

### ISSUE THREAD

**Issue by oliverpool** [patacrep/patacrep-doc#13]
@Luthaf: pourrais-tu m'accorder les droits admin sur readthedocs ? (pseudo [oliverpool](https://readthedocs.org/profiles/oliverpool/) à ajouter à la liste des "Maintainers")

C'est notamment pour créer une branche `yaml` pour la doc (avant que la branche correspondante soit mergé dans patacrep)

Merci !
(promis, je ne ferai pas de bêtises ^^)

**Comment by Luthaf** [comment]
Fait ! De mémoire, il n'y avait rien de particulier comme configuration.

**Comment by oliverpool** [comment]
Merci :+1:
