### ISSUE TITLE
Transposer les tables d'options

### ISSUE THREAD

**Issue by oliverpool** [patacrep/patacrep-doc#15]
Je trouve que les options de readthedocs dans les tableaux sont assez peu pratiques (exemple : https://patacrep.readthedocs.org/fr/yaml/book/layout.html#options-musicales)

En défilant sur le côté, on perd de vue le nom de l'option.

**Proposition** : "transposer"  les lignes et les colonnes.

Ainsi le nom des options devient l'entête, la description la 2ème ligne, *etc.*
Lors du défilement, toutes les infos concernant l'option sont visibles en même temps.

Qu'en pensez-vous ?

**Comment by paternal** [comment]
On risque d'avoir un tableau très large, qui soit peu lisible en html comme en LaTeX. On peut aussi abandonner le tableau et le remplacer par des paragraphes. Exemple :

* `diagrampage` (booléen) : Montrer la page d’accords en début de carnet. Défaut : `yes`.
* `repeatchords` (booléen) : Afficher les accords pour tous les couplets (pas disponible pour tous les chants). Défaut : `yes`.

On a comme ça de jolis paragraphes qui reviennent à la ligne quand il faut.

**Comment by oliverpool** [comment]
L'idée des paragraphe me convient.

Un peu comme [cela](https://docs.readthedocs.org/en/latest/yaml-config.html) ?

**Comment by paternal** [comment]
Par exemple. Je trouve ça un peu moins lisible que le tableau (mis à part la barre de défilement latérale), mais ça simplifie la vie, notamment pour la compilation LaTeX *et* html.

**Comment by oliverpool** [comment]
Ok, merci pour le retour !

J'essayerai de le faire quand j'aurai du temps (mine de rien c'est hyper long à écrire la doc...)

**Comment by oliverpool** [comment]
Suite dans #16
