### ISSUE TITLE
Is the diagrampage option up to date?

### ISSUE THREAD

**Issue by Grahack** [patacrep/patacrep-doc#25]
Hi,
[This section](http://patacrep.readthedocs.io/fr/latest/book/layout.html#diagrampage) doesn't seem up to date. The `songbook` ranted:

    ERROR:root:The songbook file 'gra' is not valid
    'chords' > 'diagrampage' must satisfy at least one of the following:
      must equal 'none' (was <patacrep.Rx.StrType object at 0x03857670>)
      must equal 'important' (was <patacrep.Rx.StrType object at 0x03857630>)
      must equal 'all' (was <patacrep.Rx.StrType object at 0x038574D0>)

If giving directions is simpler than fixing this I could provide a PR.

**Comment by oliverpool** [comment]
Yes, it is out of date : I forgot to update it after merging https://github.com/patacrep/patacrep/pull/212

Thanks for reporting !
