### ISSUE TITLE
Rendu des tables en LaTeX

### ISSUE THREAD

**Issue by Luthaf** [patacrep/patacrep-doc#9]
Certaines tables on un assez mauvais rendu en PDF. On peut corriger ça à la main avec  l'instruction [tabularcolumns](http://sphinx-doc.org/markup/misc.html#tables)

**Comment by oliverpool** [comment]
Est-ce que ça rejoint #15 ? (implémenté dans #16)

**Comment by Luthaf** [comment]
Yep, exactement!
